---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: tool
  labels:
    app: proxy
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - name: proxy-admin
      port: 8090
      targetPort: 8090
      nodePort: 30809
    - name: proxy-service
      port: 4993
      targetPort: 4993
      nodePort: 30993
    - name: proxy-out
      port: 80
      targetPort: 80
      nodePort: 30008
  selector:
    project: ms
    app: proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: tool
spec:
  replicas: 1
  selector:
    matchLabels:
      project: ms
      app: proxy
  template:
    metadata:
      labels:
        project: ms
        app: proxy
    spec:
      affinity:        # 配置节点亲和
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: proxydata
                    operator: In
                    values:
                      - "true"
      restartPolicy: Always
      terminationGracePeriodSeconds: 10 #当删除Pod时，等待时间
      containers:
        - name: proxy
          image: tool/lan-proxy:1.0.00-release
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_NAME
              value: proxy
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: client-data  #必须有名称
              mountPath: /app/data/ #机子内目录
            - name: config-volume
              mountPath: /app/conf/
          resources:
            limits:
              cpu: 1
              memory: 1024Mi
            requests:
              cpu: 0.5
              memory: 125Mi
          readinessProbe:              #就绪探针
            tcpSocket:
              port: 8090
            initialDelaySeconds: 20    #延迟加载时间
            periodSeconds: 5           #重试时间间隔
            timeoutSeconds: 10         #超时时间设置
            failureThreshold: 5        #探测失败的重试次数
          livenessProbe:               #存活探针
            tcpSocket:
              port: 8090
            initialDelaySeconds: 60    #延迟加载时间
            periodSeconds: 5           #重试时间间隔
            timeoutSeconds: 5          #超时时间设置
            failureThreshold: 3        #探测失败的重试次数
      volumes:
        - name: config-volume
          hostPath:
            path: /usr/local/lan-proxy/proxy-server-0.1/conf     #宿主机挂载点
        - name: client-data #挂载本机文件
          hostPath:
            path: /usr/local/lan-proxy/data      #宿主机挂载点
